changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 重大变更
      labels:
        - breaking-change
        - semver-major
    - title: 新功能
      labels:
        - enhancement
        - feature
        - semver-minor
    - title: 问题修复
      labels:
        - bug
        - fix
        - semver-patch
    - title: 文档与维护
      labels:
        - documentation
        - dependencies
        - maintenance
    - title: 其他变化
      labels:
        - "*"
